#!/bin/bash

if [ "$1" == "-v" ]; then
	manbearpig -list | while read -r line; do
		manbearpig -import github.com/assertgo/assert -mutation "$line" \
				| egrep "(found [1-9][0-9]* occur|mutating \S* to|failed to break any tests)"
	done
else
	manbearpig -list | while read -r line; do
		manbearpig -import github.com/assertgo/assert -mutation "$line" \
				| egrep "(failed to break any tests)"
	done
fi
